import { defineField, defineType } from "sanity";

export const heroBlock = defineType({
  name: "heroBlock",
  title: "Hero Section",
  type: "object",
  fields: [
    defineField({ name: "eyebrow",    title: "Eyebrow Label", type: "string" }),
    defineField({ name: "heading",    title: "Heading",       type: "string" }),
    defineField({ name: "subheading", title: "Subheading",    type: "text", rows: 2 }),
    defineField({ name: "ctaLabel",   title: "CTA Button Label", type: "string", initialValue: "Join Our League" }),
    defineField({ name: "ctaHref",    title: "CTA Button Link",  type: "string", initialValue: "#contact" }),
    defineField({
      name: "backgroundImage",
      title: "Background Image (single)",
      description: "Use this for a single static image. For a crossfading slideshow, use Background Images below — it takes precedence.",
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alt Text", type: "string" }),
      ],
    }),
    defineField({
      name: "backgroundImages",
      title: "Background Images (slideshow)",
      description: "Upload two or more images to crossfade between them. Leave empty to use the single image above.",
      type: "array",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({ name: "alt", title: "Alt Text", type: "string" }),
          ],
        },
      ],
    }),
    defineField({
      name: "backgroundInterval",
      title: "Seconds per image",
      type: "number",
      initialValue: 6,
      description: "How long each image stays fully visible before crossfading.",
      validation: (R) => R.positive(),
    }),
    defineField({
      name: "backgroundTransition",
      title: "Crossfade Duration (seconds)",
      type: "number",
      initialValue: 1.5,
      description: "How long each fade transition takes. Lower = snappier, higher = silkier.",
      validation: (R) => R.positive(),
    }),
    defineField({
      name: "backgroundOpacity",
      title: "Background Image Opacity",
      type: "number",
      initialValue: 1,
      description: "Pick how visible the image should be. Only affects the image layer — text stays crisp.",
      options: {
        list: [
          { title: "0% — invisible", value: 0 },
          { title: "10%",  value: 0.1 },
          { title: "20%",  value: 0.2 },
          { title: "30%",  value: 0.3 },
          { title: "40%",  value: 0.4 },
          { title: "50%",  value: 0.5 },
          { title: "60%",  value: 0.6 },
          { title: "70%",  value: 0.7 },
          { title: "80%",  value: 0.8 },
          { title: "90%",  value: 0.9 },
          { title: "100% — full",  value: 1 },
        ],
        layout: "dropdown",
      },
      validation: (R) => R.min(0).max(1),
    }),
    defineField({
      name: "backgroundBlendMode",
      title: "Background Blend Mode",
      type: "string",
      initialValue: "normal",
      description: "How the background image blends with the navy overlay. 'Normal' keeps the image as-is.",
      options: {
        list: [
          { title: "Normal",     value: "normal"     },
          { title: "Multiply",   value: "multiply"   },
          { title: "Screen",     value: "screen"     },
          { title: "Overlay",    value: "overlay"    },
          { title: "Soft Light", value: "soft-light" },
          { title: "Hard Light", value: "hard-light" },
          { title: "Darken",     value: "darken"     },
          { title: "Lighten",    value: "lighten"    },
          { title: "Luminosity", value: "luminosity" },
          { title: "Color",      value: "color"      },
          { title: "Difference", value: "difference" },
        ],
        layout: "dropdown",
      },
    }),
    defineField({
      name: "image",
      title: "Image (below headline)",
      description: "Optional. Sits between the headline and the subheading.",
      type: "image",
      options: { accept: "image/svg+xml,image/png,image/webp,image/jpeg" },
      fields: [
        defineField({ name: "alt", title: "Alt Text", type: "string" }),
      ],
    }),
    defineField({
      name: "lottie",
      title: "Lottie Animation (below headline)",
      description: "Optional. Upload a .lottie or .json file. Sits in the same slot as the image — takes precedence over image if both are set.",
      type: "file",
      options: { accept: ".lottie,.json,application/json" },
      fields: [
        defineField({ name: "loop",     title: "Loop",     type: "boolean", initialValue: true }),
        defineField({ name: "autoplay", title: "Autoplay", type: "boolean", initialValue: true }),
      ],
    }),
    defineField({
      name: "mediaMaxWidth",
      title: "Media Max Width (px)",
      type: "number",
      initialValue: 320,
      description: "Constrains the below-headline image or Lottie.",
    }),
  ],
  preview: {
    select: { title: "heading" },
    prepare(s) { return { title: `Hero — ${s.title ?? "Untitled"}` }; },
  },
});
